version: '3'
services:
  f-service:
    build:
      context: ./services/f-api
      dockerfile: Dockerfile
    container_name: f-api
    ports:
      - "8000:8000"
  s-service:
    build:
      context: ./services/s-api
      dockerfile: Dockerfile
    container_name: s-api
    ports:
      - "8001:8001"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "8080:8080" 
